---
- name: apply-sysctl-rules
  command: "sysctl --system" 

- name: keycloak-systemd
  systemd: name=keycloak state=restarted daemon_reload=yes enabled=yes

- name: keepalived-systemd
  systemd: name=keepalived state=restarted daemon_reload=yes enabled=yes

- name: nginx-systemd
  systemd: name=nginx state=restarted daemon_reload=yes enabled=yes